added api specs and overview
platf0rm/platform pull request #9
Opened 2017-03-25 11:59 UTC by kimerran

for review

2017-03-25 20:16 UTC, ghost requested changes
Please put requirements for the parameters such as data types.

2017-03-25 20:16 UTC, vkeusebio commented on docs/api-spec/post-votes-by-comment.md
> +{ "result": "ok" }
For consistency and verbosity, please don't use single-line examples. See https://github.com/platf0rm/platform/pull/9/commits/b997e368b5aeba61829257987a01defda3938f08#diff-03db1675cc9d339a9c38c4af5f3c5a05 as an example.

2017-03-26 00:22 UTC, ac-opensource approved these changes
LGTM after fixing @vkeusebio's comment

2017-03-26 01:53 UTC, kimerran commented
@vkeusebio I made some [formatting changes](https://github.com/platf0rm/platform/pull/9/commits/3e88d957daf42eebd75ee181ec7855ca6dabd9c2). please review again. thanks

2017-03-26 02:37 UTC, ghost approved these changes

2017-03-26 02:38 UTC, vkeusebio commented
@kimerran LGTM, merging. Thanks!

2017-03-26 02:38 UTC, merged